mallchat:
  mysql:
    ip: 192.168.230.7
    port: 3306
    db: mall_chat
    username: root
    password: Mh.123456
  redis:
    host: 192.168.230.7
    port: 6379
    password: ManHui20!&

# 微信公众号配置
wx:
  mp:
    # 内网穿透域名
    domain: https://788sl31695.yicp.fun
    callback: /chat/officialAccount/callBack
    # 过期时间10分钟
    codeExpirationTime: 6000
    config:
      appId: wx0c55904dbb1ae525
      secret: a0a0b2ee48c6df7262a540096962ee3b
      # 接口配置的token值
      token: efc8ed04858541f28424d1746d8aaf22
      # 接口配置里的EncodingAESKey值，测试号不用（线上的服务需要配置）
      aesKey: OPqbNagjyh1aONFOAUqHUG8mJGOZD7ZzxLF64UvLStN

# netty配置
netty:
  port: 8090
  bossExecutor: 1
  workerExecutor: 4
  timeout: 30000